name: Build Plugin

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out plugin code
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Ninja
        uses: llvm/actions/install-ninja@v1

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build Plugin (Release)
        run: cmake --build build --config Release --parallel

      - name: Upload VST3 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mdottyfx-Windows-VST3
          path: build/mdottyfx_artefacts/Release/VST3/**
